### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by somefunAgba** [leo-colisson/proof-at-the-end#12]
How do you use this package to declare standalone proofs in the appendix with reference to the section or equation in the section where it was stated?

**Comment by tobiasBora** [comment]
Oh, I misunderstood your definition of standalone, I thought you wanted to have it separately in a new file.

So the environment `proofEnd` relies indeed on the fact that there is a theorem/lemma/… before, as otherwise it would not even know what to link to. I can imagine two ways to solve your issue. The simpler might be to simply use `\textEnd{…}`:
```
\textEnd{
    Any text you wish to push to appendix.
}
```
and put inside the proof. Here is an example producing:

![image](https://user-images.githubusercontent.com/2164118/221613533-464c8a11-388d-4c18-a3c0-f621c3d7bcd8.png)


```
\documentclass{article}

\usepackage{amsmath}
\usepackage{xparse} % Not needed with recent LaTeX
\usepackage{amsthm}

% Create new theorems, or use ntheorem/thmtools/...
\newtheorem{thm}{Theorem}[section]
% Default uses autoref, but you can also use cleveref, see the documentation.
% Say to autoref that "thm" are Theorems.
\newcommand{\thmautorefname}{Theorem}

%% Load the library. createShortEnv automatically creates the shortcuts
%% thmE, theoremE, lemmaE, propositionE, corollaryE, proofE. See \newEndThm for more details.
\usepackage[createShortEnv]{proof-at-the-end}
\usepackage{hyperref}
\usepackage{cleveref}

\begin{document}

\section{Theorems}

Here is an equation:
\begin{align}
  1 + 1 + 1 = 3\label{eq:myequation}
\end{align}
See the proof in \cref{sec:sectionProof}.

\textEnd{
  \subsection{Proof of \cref{eq:myequation}}\label{sec:sectionProof}
  We prove here \cref{eq:myequation}:
  \begin{proof}
    We know that $1+1=2$, and $2+1=3$, so $1+1+1 = 3$.
  \end{proof}
}

\section{Proofs}
\printProofs

\end{document}
```

In case you use this a lot, you can define your own function, like:
```
%% \standaloneProof{label equation}{proof}
\NewDocumentCommand{\standaloneProof}{mm}{%
  See the proof in \cref{subsec:#1}.

  \textEnd{
    \subsection{Proof of \cref{eq:#1}}\label{subsec:#1}
    We prove here \cref{eq:#1}:
    \begin{proof}
      #2.
    \end{proof}
  }  
}
```
this way later you only have to type:
```
Here is an equation:
\begin{align}
  1 + 1 + 1 = 3\label{eq:myequation}
\end{align}
\standaloneProof{myequation}{
  We know that $1+1=2$, and $2+1=3$, so $1+1+1 = 3$.
}
```
to get the same result.

Would it solve your issues?

**Comment by somefunAgba** [comment]
Thanks @tobiasBora, I have done something like this with \textEnd, as it looks as if that's the only option.

I would prefer if there is a redefined proof environment that is not dependent on just the theorem environment and can easily be cross referenced with full links like the Theorem environment in the Appendix.

e.g:
```
3. Algorithms
lorep isum...
See proof of Section 3 in Appendix B
```

where proof, section3, and Appendix B are clickable.

**Comment by somefunAgba** [comment]
```
\NewDocumentCommand{\anyProof}{+m+m+m+m}{%
  \emph{See \hyperref[prf:#1]{proof} of \Cref{#1} in \hyperref[#3]{Appendix~\ref*{#3}}}.

  \textEnd[category=#2]{
    \paragraph{\normalfont{\emph{Proof of \hyperref[#1]{\Cref{#1}} }}}\label{prf:#1}
    \begin{proof}
      #4\qed
    \end{proof}
  }  
```

**Comment by tobiasBora** [comment]
Ok, good to see that it works for you. My main issue with putting this in the main package is that it seems to depend a lot on the use-case, some people might want a new section, others might want a paragraph, others might want nothing… and at the end it might be as easy as just writing the command themself. But I might try to provide more options later when I'll add some more optinos (I plan to add some functions later to easily produce different versions depending on whether the paper is the published one or the preprint version… I already have some code but I need to make it nicely fit with the library)
