### ISSUE TITLE
[BUG] Numbering of restated theorems is not the same as in the original theorem using jmlr

### ISSUE THREAD

**Issue by joshchang** [leo-colisson/proof-at-the-end#13]
**Describe the bug**
The numbering doesn't reset. See the example below where it is Lemma 1,2 in main text and is Lemma 3,4 in the appendix when restated

**To Reproduce: Minimal Working Example**
Simple example:
```latex
\documentclass[pmlr]{jmlr}% new name PMLR (Proceedings of Machine Learning)
\usepackage[createShortEnv]{proof-at-the-end}


\begin{document}


\begin{lemmaE}[Something here][end,restate,text link section]
\end{lemmaE}
\begin{proofE}
The proof is self-evident
\end{proofE}

\begin{lemmaE}[Something else here][end,restate,text link section]
\end{lemmaE}
\begin{proofE}
The proof is also self-evident
\end{proofE}

\appendix


\section{Proofs}

\printProofs

\end{document}
```

The ouput is:

Lemma 1 (Something here)
See proof in section A .
Lemma 2 (Something else here)
See proof in section A .
Appendix A. Proofs
Lemma 3 (Something here)
Proof [Proof of Theorem 1]The proof is self-evident
Lemma 4 (Something else here)
Proof [Proof of Theorem 2]The proof is also self-evident

**Version**
Overleaf texlive 2022

Version of `proof-at-the-end`: master

**Comment by joshchang** [comment]
Works if I define my own counters

**Comment by dpo** [comment]
Could you please show how you solved the problem?

**Comment by joshchang** [comment]
I added these to the start of the appendix

\setcounter{lemma}{0}
\setcounter{theorem}{0}
\setcounter{equation}{0}

**Comment by tobiasBora** [comment]
Note that you might want to use cref instead and add `section` to the counters taken il nto account by thm-restate as explained here https://github.com/leo-colisson/proof-at-the-end/issues/14#issuecomment-1676059612
