### ISSUE TITLE
[Help needed] proof at the end formatting

### ISSUE THREAD

**Issue by danieleavitabile** [leo-colisson/proof-at-the-end#17]
This is not a bug, but rather a request for help. Would it be possible to get some help on the following question

https://tex.stackexchange.com/questions/731239/proof-at-the-end-formatting

I try to explain why the current default replacement text for a proof in the main text is not very handy to me, and would like to change it somehow.

**Comment by tobiasBora** [comment]
Hi, my understanding is that your issue has been solved there. I can confirm that the proposed solution is correct, I just added in comments a slightly quicker solution that avoids the creation of a new style with `\pratendSetGlobal{text link=…}`.
