### ISSUE TITLE
restate results in "see proof in Equation A" instead of "see proof in Appendix A"

### ISSUE THREAD

**Issue by RJTK** [leo-colisson/proof-at-the-end#2]
I am using
```
\begin{theoremEnd}[text link section, restate]{proposition}
\end{theoremEnd}
\begin{proofEnd}
\end{proofEnd}
```
and where the proof would usually go is written "see proof in Equation A".  Using options `[text link section]` without `restate` results in "see proof in Appendix A" as expected.

**Comment by tobiasBora** [comment]
Thanks for the report. I think that it's quite hard for the script to reliably get the section name sometimes, and hyperref seems to be quite bad to solve the problem... I tried to write a version with `cleveref` instead, that seems to solve the text issue (there is still an issue with the link, I asked [here](https://tex.stackexchange.com/questions/553394/reliably-add-a-label-to-the-current-section-even-if-the-label-is-not-placed-rig) for more help).

Could you please try the version in the branch `version_cleveref` to see if the problem is fixed? You should be able to use that version by just copy/pasting the file `proof-at-the-end.sty` in your project.

If it does not work, could you include a minimal example? For references, here is mine:

```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[english]{babel}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{amsthm}
\usepackage{thmtools}

\declaretheorem[name=Definition]{definition}
\declaretheorem[name=Theorem]{theorem}
\declaretheorem[name=Lemma,sibling=theorem]{lemma}

\usepackage{proof-at-the-end}

\usepackage[colorlinks]{hyperref}
\usepackage{cleveref}

\begin{document}

\section{Une section}

\begin{theoremEnd}[text link section, restate]{theorem}
\end{theoremEnd}
\begin{proofEnd}
  Here is the proof of the theorem
  \begin{equation}
    1+1=2
  \end{equation}
\end{proofEnd}

\appendix
\section{Proofs}
Hello
\begin{equation}
  1+1=2
\end{equation}

\printProofs
\label{section:shouldbeappendixA}

\end{document}
```

**Comment by haroldship** [comment]
I have the same issue without restate:

`\theoremstyle{plain}
\newtheorem{thm}{Theorem}
\providecommand*\thmautorefname{Theorem}

\NewDocumentEnvironment{thmE}{O{}O{}+b}{%
    \begin{theoremEnd}[proof at the end,text link section]{thm}[#1]%
        #3%
    \end{theoremEnd}%
}{}

\newtheorem{prop}[thm]{Proposition}
\providecommand*\propautorefname{Proposition}

\NewDocumentEnvironment{propE}{O{}O{}+b}{%
    \begin{theoremEnd}[proof at the end,text link section]{prop}[#1]%
        #3%
    \end{theoremEnd}%
}{}

\NewDocumentEnvironment{proofE}{O{}+b}{%
    \begin{proofEnd}[#1]%
        #2%
    \end{proofEnd}%
}{}`

**Comment by tobiasBora** [comment]
@haroldship Thanks for your report. Can you try the `cleveref` based solution?

By the way, you can always solve this problem differently by customizing the link using something like:
```
\pgfkeys{/prAtEnd/local custom defaults/.style={
    text link={See \hyperref[proof:prAtEnd\pratendcountercurrent]{proof} in \autoref{sec:yourAppendixSection}.}
  }
}
```

**Comment by tobiasBora** [comment]
The latest version should solve the issue (just copy/paste the `proof-at-the-end.sty` file at the root of your project). If not, let me know and provide a **complete** MWE.

**Comment by haroldship** [comment]
Hi Tobias

It did not help. I will try to prepare an example later.

**Comment by tobiasBora** [comment]
Oh really? Strange, then it would be great if you provide a MWE.

**Comment by haroldship** [comment]
`\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[english]{babel}

\title{Proof at the End}
\author{Harold Ship}

% math stuff
\usepackage[fleqn]{amsmath}
\usepackage{amsfonts} % for mathbb
\usepackage{mathtools} % loads amsmath plus other tools
\usepackage{fixmath} % fix greek letters
\usepackage{relsize} % for \mathlarger
\usepackage{bm} % for \bm (bold math)

\usepackage{amsthm} % math theorems and theorem environments
\usepackage{proof-at-the-end} % help put proof in appendix

\usepackage{hyperref}
\usepackage{cleveref}

\theoremstyle{definition}
\newtheorem{example}{Example}
\providecommand*\exampleautorefname{Example}

\theoremstyle{plain}
\newtheorem{thm}{Theorem}
\providecommand*\thmautorefname{Theorem}

\NewDocumentEnvironment{thmE}{O{}O{}+b}{%
    \begin{theoremEnd}[proof at the end,text link section,#2]{thm}[#1]%
        #3%
    \end{theoremEnd}%
}{}

\newtheorem{prop}[thm]{Proposition}
\providecommand*\propautorefname{Proposition}

\NewDocumentEnvironment{propE}{O{}O{}+b}{%
    \begin{theoremEnd}[proof at the end,text link section,#2]{prop}[#1]%
        #3%
    \end{theoremEnd}%
}{}

\NewDocumentEnvironment{proofE}{O{}+b}{%
    \begin{proofEnd}[#1]%
        #2%
    \end{proofEnd}%
}{}

% \pgfkeys{/prAtEnd/local custom defaults/.style={
%     text link={See \hyperref[proof:prAtEnd\pratendcountercurrent]{proof} in \autoref{appendix:proofs}.}
%   }
% }

%=============================================================================
%
% This is where the document is
%
%=============================================================================
\begin{document}

\maketitle

\begin{abstract}
This is an abstract
\end{abstract}


%=============================================================================
% Introduction
%=============================================================================
\section{Introduction}
\label{sec:introduction}


%=============================================================================
%=============================================================================
\section{Another Section}
\subsection{Example}
\example{
    \label{ex:example}
    An example.
}    

Proofs of the following can be found in \Cref{appendix:proofs}.

\begin{propE}
    \label{prop:prop-a}
    Prop A
\end{propE}

\begin{proofE}
    Proof A
\end{proofE}

\begin{table}[!hptb]
    \centering
    \begin{tabular}{ll}
        Column & Column \\
        \hline
        x & y \\
        a & b
    \end{tabular}
    \caption{A table}
\end{table}

\begin{propE}
    \label{prop:prop-b}
    Prop B.
\end{propE}

\begin{proofE}
    Proof B.
\end{proofE}

\begin{propE}
    Prop C.
\end{propE}

\begin{proofE}
    Proof C.
\end{proofE}


\begin{thmE}
    \label{thm:theorem-d}
    Theorem.
\end{thmE}

\begin{proofE}
   Proof proof tada qed.
\end{proofE}

\begin{thmE}
    \label{thm:theorem-e}
    Another theorem.
\end{thmE}

\begin{proofE}
    TBD
\end{proofE}



% =============================================================================
% Results
% =============================================================================
\section{Results}
\label{sec:results}

\appendix

\section{Proofs}
\label{appendix:proofs}

\printProofs


%\bibliographystyle{plain}
%\bibliography{references}
\end{document}
`

**Comment by tobiasBora** [comment]
Thanks for the report. So just to make sure that we see the same thing, do you confirm that you see `See proof in Appendix A` for the first proof, and `See proof in section A` (instead of `Appendix A`) later?

This is indeed quite strange, I need to understand why it's written only the first time Appendix. However, note that `cref` does not have this bug: your example compiles fine if you load the package with `commandRef=Cref`:
```
\usepackage[commandRef=Cref]{proof-at-the-end}
```

![image](https://user-images.githubusercontent.com/2164118/152794963-28273003-92ca-49f2-aaeb-caf5620221fb.png)

However, I still want to support both `cleveref` and `hyperef`'s (via `autoref`), so I will try to investigate further.

**Comment by haroldship** [comment]
Hi Tobias
The problem you described is exactly my problem, and setting commandRef=Cref
fixed it. Thanks.
