### ISSUE TITLE
Claim numbers disappearing within proofEnd environment

### ISSUE THREAD

**Issue by anthonimes** [leo-colisson/proof-at-the-end#4]
Hi!

First of all, thanks a lot for the package, I've been looking for something like this for a while now. :) 

I have a (maybe dumb) question about numbering: I have a proofEnd environment for a Theorem, which itself contains some claim environments. 

These environments are correctly numbered when the proof is in plain text (using the normal option of your package), but numbering disappears when I push the proof at the end of the document. 

Am I doing something wrong? I tried to surround the claim with a theoremEnd environment but the issue remains. 

Thanks!

**Comment by anthonimes** [comment]
Oh, it was actually the LaTeX style I am using that caused the issue. I'm really sorry, it did not occur to me that the template could decide not to number claim environments...

**Comment by tobiasBora** [comment]
No problem. I was actually trying to reproduce the bug without success. By the way, if you fill a bug next time, do not hesitate to add a Minimal Working Example, it really helps me to pin point quickly the bugs ;-)
