### ISSUE TITLE
demo.tex does not work with MikTex

### ISSUE THREAD

**Issue by sjkillen** [leo-colisson/proof-at-the-end#6]
**Describe the bug**
demo.tex does not work with MikTex; raises errors

**To Reproduce: Minimal Working Example**

`pdflatex demo.tex`

Output:
```
! LaTeX3 Error: Control sequence \ArgumentSpecification already defined.

For immediate help type H <return>.
 ...                                              
                                                  
l.1828 \tl_new:N \ArgumentSpecification
                                       
? 
```

**Version**
Output of `latex --version`:

```
MiKTeX-pdfTeX 4.2 (MiKTeX 20.12)
```

Version of `proof-at-the-end`: 2019/05/21 and latest

**Comment by tobiasBora** [comment]
Thanks for your report. You compiled it by first cloning this repository? Can you try to remove the `xparse.sty` file? (it was provided only to make sure old LaTeX distribution could use the package).

I'm thinking that maybe in latest MakTex version xparse is loaded automatically...

**Comment by sjkillen** [comment]
Thanks for having a look at this. Removing xparse.sty seemed to fix it.
The demo also works when I remove \usepackage{xparse} and \RequirePackage{xparse} so I think you may be right about the automatic loading.

**Comment by tobiasBora** [comment]
Yes, I asked more details [here](https://tex.stackexchange.com/questions/600495/how-to-provide-xparse-on-both-old-and-recent-latex-distributions/600512#600512), and according to [this thread](https://tex.stackexchange.com/questions/600353/newdocumentcommand-without-xparse), most of xparse was integrated in LaTeX in 2020-10-01. Also, there is a License issue (not allowed to distribute only the .sty apparently), so I guess I'll juste remove xparse from this repository, thanks.
